### PR TITLE
Add 3mm blead and slug to each template and add temp 80mm x 120 mm template

### PR DESCRIPTION
**Pull request by sydseter**
In this pull-request:

- I added a 3mm blead margin to ensure the decks can be properly printed. bleed settings wasn't defined before, They should be there now.  
- I also added 3mm slug.
- Added a new template for printing 80mm x 120mm decks similar to the Agile Stationary ecommerce deck
- Added cases for the 80mm x 120mm decks

[owasp_cornucopia_mobileapp_1.00_case_80x120mm.pdf](https://github.com/OWASP/cornucopia/files/15462739/owasp_cornucopia_mobileapp_1.00_case_80x120mm.pdf)
[owasp_cornucopia_webapp_2.00_case_80x120mm.pdf](https://github.com/OWASP/cornucopia/files/15462741/owasp_cornucopia_webapp_2.00_case_80x120mm.pdf)
[owasp_cornucopia_webapp_cards_en_1.00_80x120mm.pdf](https://github.com/OWASP/cornucopia/files/15462742/owasp_cornucopia_webapp_cards_en_1.00_80x120mm.pdf)
[owasp_cornucopia_mobileapp_cards_en_1.00_80x120mm.pdf](https://github.com/OWASP/cornucopia/files/15462743/owasp_cornucopia_mobileapp_cards_en_1.00_80x120mm.pdf)

### CODE REVIEW

**Comment by sydseter** [comment]
pixeebot is taken care of in https://github.com/OWASP/cornucopia/pull/560

**Review by cw-owasp — COMMENTED** [review]
I downloaded the IDMLs for the EN leaflets and cards. The leaflets files look fine. But, should the white area on the card faces also be extended out to the bleed boundary (both web and mobile).

Also, when I downloaded the "pr565-owasp_cornucopia_mobileapp_cards_en_1.00_static.idml", I received a missing linked file warning for 'C:/Users/JohanSydseter/Documents/cornucopia/cornocopia masvs back of card elements.svg"

**Review by cw-owasp — APPROVED** [review]

**Comment by sydseter** [comment]
@cw-owasp great catch! The missing link file was not intended.

**Comment by sydseter** [comment]
> I downloaded the IDMLs for the EN leaflets and cards. The leaflets files look fine. But, should the white area on the card faces also be extended out to the bleed boundary (both web and mobile).
> 
> Also, when I downloaded the "pr565-owasp_cornucopia_mobileapp_cards_en_1.00_static.idml", I received a missing linked file warning for 'C:/Users/JohanSydseter/Documents/cornucopia/cornocopia masvs back of card elements.svg"

I don't think it is necessary to extend the white area. From what I understand, white will be ignored when sending document to print, so the printer shouldn't try to print white. It is possible to override this, but I believe that is the default option.

**Review by cw-owasp — APPROVED** [review]

**Comment by cw-owasp** [comment]
Ah yes, I remember now "white==blank==no ink".

**Comment by sydseter** [comment]
No real change. Just squashed all the commits in order to save storage.

**Comment by rewtd** [comment]
> No real change. Just squashed all the commits in order to save storage.

LGTM :shipit:

**Review by rewtd — APPROVED** [review]
:shipit:

**Pull request merged**
