### PR TITLE
Adding Cornucopia leaflets for all language decks

### PR DESCRIPTION
**Pull request by sydseter**
In this pull request:

- This is the leaflet. I needed to use 20 pages for the leaflet. The index does not point to every chapter in the leaflet due to the differences between the various translations. These are the files as pdfs:
  - [owasp_cornucopia_ecommerce_cards_en_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046658/owasp_cornucopia_ecommerce_cards_en_1.30_leaflet.pdf)
  - [owasp_cornucopia_ecommerce_cards_es_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046660/owasp_cornucopia_ecommerce_cards_es_1.30_leaflet.pdf)
  - [owasp_cornucopia_ecommerce_cards_fr_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046661/owasp_cornucopia_ecommerce_cards_fr_1.30_leaflet.pdf)
  - [owasp_cornucopia_ecommerce_cards_nl_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046662/owasp_cornucopia_ecommerce_cards_nl_1.30_leaflet.pdf)
  - [owasp_cornucopia_ecommerce_cards_no-nb_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046663/owasp_cornucopia_ecommerce_cards_no-nb_1.30_leaflet.pdf)
  - [owasp_cornucopia_ecommerce_cards_pt-br_1.30_leaflet.pdf](https://github.com/OWASP/cornucopia/files/15046664/owasp_cornucopia_ecommerce_cards_pt-br_1.30_leaflet.pdf)
- I have corrected the syntax in several of the language. There was some use of quotation that was problematic. I also had to add some translations as they were missing for the leaflet.
- I removed the dynamic card decks from the release since they do not contain any qr codes and still are to be considered wip.
- I needed to move the list formating out of the translations and into the templates in order to ensure consistency and better styling.

### CODE REVIEW

**Comment by sydseter** [comment]
Fixes #307

**Review by rewtd — APPROVED** [review]
This looks good! I've found a brand new, original deck with a pamphlet. Do you want me to send it to you?

**Comment by sydseter** [comment]
Hi, yes, that would be good. I think it is probably fine, but it would be good to have a look  to make sure.

**Comment by sydseter** [comment]
Btw. anyone wanting to print the leaflet will need to make minor adjustments to pages 11-19 and the index in order for the leaflet to look good. Reason being the variability of text translation lengths does not match the index on the leaflet. I haven’t found a way to make a dynamic index in Indesign yet that can be built like this, but I’ll look into it.

**Pull request merged**
