### PR TITLE
Fix the bridge layout for the cases.

### PR DESCRIPTION
**Pull request by sydseter**
In this pull-request:

- This tuck box bridge case layout was given to me by Devika at Agilestationary on request and should fit perfectly if anyone wants to print bridge size decks. 

[owasp_cornucopia_mobileapp_1.00_case_bridge.pdf](https://github.com/user-attachments/files/16932078/owasp_cornucopia_mobileapp_1.00_case_bridge.pdf)
[owasp_cornucopia_webapp_2.00_case_bridge.pdf](https://github.com/user-attachments/files/16932079/owasp_cornucopia_webapp_2.00_case_bridge.pdf)

### CODE REVIEW

**Review by rewtd — DISMISSED** [review]
:shipit:

**Comment by sydseter** [comment]
Found a 1 pixel line that popped up when opening the pdf in a different viewer. Removed it and did a new export.

**Review by rewtd — APPROVED** [review]
:shipit:

**Comment by cw-owasp** [comment]
We have a growing list of commercial donors of artwork, text and code... Travelex (long time ago), Blackfoot, SecureDelivery, DotNetLab, Agile Stationery, maybe others? I think we need to make sure we are even-handed with all of these in credits in the leaflet, on the website, and so on.

**Comment by sydseter** [comment]
@cw-owasp sure. Let's see how we can properly do this. It might be better to give proper credits on the website and comment on this on the leaflets and guides.

**Pull request merged**
