### PR TITLE
Translation adaptations and completions for multiple languages and link corrections to ensure the translations are compatible with both ASVS v4 and v3

### PR DESCRIPTION
**Pull request by sydseter**
## This pull request contains

- Multi-language fixes for #13
- Adapt the static and dynamic templates so that they can be printed correctly in multiple languages.
- Complete the Spanish language translations.
- Changed the docx template margins for the cards.
- Fix copy&past errors in the Spanish translation.
- Removed wrongly formated text that was included in the translations.
- Added generated output after applying the changes.

### Multilanguage templated adaptations
Previously the translated docx versions had issues because the docx templates weren't really adapted to work with multiple languages. I therefor added new table rows and moved the text from the last table to the first table in the docx templates so that the page breaks comes where you would expect them. This means that you know can add more languages without having to worry about the docx templates. The previous versions would also have empty space spill over on the next page. In order to fix this, the column height has been adjusted and white space removed so that the text doesn't spill.

#### **Previously:**

issues with page breaks 2

#### **Now:**

issues with page breaks 2 fixed

#### **Text and white space spilling issues has now been fixed**

**ex. 1:**
empty space

**ex. 2:**
issues with page breaks

### ASVS v4 fixes for links
Previously the link references where quite long. This would break the docx templates. In order to make the templates work with multiple languages, the links had to be shorten to not break the columns in the table. Some of the links also referred only to ASVS v3. In order for the templates to be backward compatible the references no points to the OWAS ASVS repository where both the v3 and the v4 printable documents can be downloaded.

#### **Link Examples**
 
**previously ex. 1:**
issues with links

**now ex. 1:**
issues with links fixed

**previously ex. 2:**
old links

**now ex. 2:**
old links fixed

### Removal of included bullet points and tab spaces in the translation that shouldn't have been included.

Some of the translations has the bullet points included. 
The French translation has several tabs that should have been a single space instead.
This has been cleaned up.

### CODE REVIEW

**Comment by sydseter** [comment]
I am not sure that test will work since there is no reference to the branch during a pull-request event. Tried to change it, but I did update all the output files at the end here, so they should be ok.

**Comment by sydseter** [comment]
You mentioned that the bulletpoints might have been used in the leaflet, although that might be true, there is no automatic generation of the leaflet, there is just an original that always have been manually edited. see: https://github.com/OWASP/cornucopia/blob/master/resources/originals/OWASP%20CORNUCOPIA%20Folded%20Leaflet%20v1.20-EN.idml
Even if we where to create an automatic generation of the leaflet, I think we still should opt for not having the formatting like bullet-points in the translations. Reason being that it cause issues for how the text breaks and flows for the various templates. ex, In the docx you end up with double bullet, points or whitespace that breaks the translated sentences in places you wouldn't want it to. e.g:

ex 1:
white space issues2

ex 2:
white space issues


 I think it would be better to edit the templates and add bullet points there when that is needed. Keeping the formatting and links in the templates and the translated content in the yaml files will make it much easier to add new translations.
 Otherwise you will end up adapting the templates when adding new translations.

**Comment by sydseter** [comment]
Here are the same examples as they look like after I cleaned them up:

ex 1:
white space issues2 fix


ex 2:
white space issues fix

**Comment by sydseter** [comment]
I understand that we should maybe keep the cleanup in a separate pr, but it's better to have all of it here, since what we care the most about here, is to check that the templates works with **all** of the translations, this way, it makes it easier to see that the output, does in deed works across all of the printable files. I couldn't just do the fixes for ASVS v4 since the result wouldn't be printable.

**Comment by sydseter** [comment]
I may have gone a bit overboard changing AZ3 description for the english translation using "he" instead of "they". "they" is of course better.

**Comment by rewtd** [comment]
> You mentioned that the bulletpoints might have been used in the leaflet, although that might be true, there is no automatic generation of the leaflet, there is just an original that always have been manually edited. see: https://github.com/OWASP/cornucopia/blob/master/resources/originals/OWASP%20CORNUCOPIA%20Folded%20Leaflet%20v1.20-EN.idml 

There should have been an automated generation of the leaflet, although I didn't do the work on that. That original file was indeed manually created. I agree with the rest of what you wrote however.

**Review by rewtd — APPROVED** [review]
Lots to look at here and it's probably good to have this in the main branch anyhow.

**Pull request merged**
