### PR TITLE
Adding Italian translation

### PR DESCRIPTION
**Pull request by rdallaglio**
Added Italian translation

### CODE REVIEW

**Review by rewtd — APPROVED** [review]

**Review by cw-owasp — APPROVED** [review]
Thank you very much for adding this translation

**Comment by rewtd** [comment]
@sydseter can you take a look at the failing test today? Otherwise I'll take a look later this week.

**Comment by sydseter** [comment]
sure one sec.

**Comment by sydseter** [comment]
Moved branch to owasp origin and created a new pull-request: https://github.com/OWASP/cornucopia/pull/836

This can be closed when #836 is merged.

**Comment by sydseter** [comment]
https://github.com/OWASP/cornucopia/pull/836

**Pull request merged**
