### PR TITLE
Adding hypothesis test example and start on the first cornucopia fuzzer

### PR DESCRIPTION
**Pull request by sydseter**

### CODE REVIEW

**Comment by sydseter** [comment]
This still require a bit more work. Hard to test this out. The tool behaves very differently locally.

**Comment by sydseter** [comment]
I got the fuzzer working and added the first test. We need to improve the coverage as we add more code.
At least it works now.

**Review by rewtd — APPROVED** [review]
This is good work!

**Comment by sydseter** [comment]
related to #308

**Pull request merged**
