### PR TITLE
Prepare for 2.0 release and mobile app release and shorten the build time.

### PR DESCRIPTION
**Pull request by sydseter**
Instead of building everything, let's just build what we need to build and test.

### CODE REVIEW

**Review by rewtd — CHANGES_REQUESTED** [review]
Perhaps we should also remove the "dynamic" from the -all list for now?

**Comment by sydseter** [comment]
Yeah that's a good idea.

**Comment by sydseter** [comment]
done!

**Review by rewtd — APPROVED** [review]
LGTM - we do need copi up on owasp.org for this to work however...

**Comment by sydseter** [comment]
@rewtd This may not be the right way to generate the qr codes. They need to be embedded into the idml and docx files and indesign already have a way of generating qr codes. I am wondering whether we should remove it.

**Comment by rewtd** [comment]
100%

**Pull request merged**
